# check ./resa/config.py
seed: 42

lora_r: 32
lora_alpha: 128
lora_dropout: 0.05
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- down_proj
- up_proj
- gate_proj
learning_rate: 1e-6
num_epochs: 2
batch_size: 1 # no padding to align with SAE fine-tuning
logging_steps: 1
save_steps: 500